######################## default configuration ####################
# The base URL of your site (required). This will be prepended to all relative URLs.
baseURL = "https://natureinparadise.github.io/"
# Title of your website (required).
title = "Dave Klinges | Ecology and Conservation"
# Your theme name
theme = "airspace-hugo"
# post pagination
pagination.PagerSize = 4
# post excerpt
summaryLength = 30
# disqus short name
disableLanguages = []
timeout = "500s"

########################### Services #############################
[services]
[services.googleAnalytics]
ID = 'G-MEASUREMENT_ID' # see https://gohugo.io/templates/internal/#configure-google-analytics

################################# Output formats ##############################
# Documentation: https://gohugo.io/templates/output-formats/#customizing-output-formats

[outputs]
home = ["HTML"]

################################# Markup ######################################
# Documentation: https://gohugo.io/getting-started/configuration-markup

[markup.goldmark.renderer]
# Allow "unsafe" HTML in Markdown
unsafe = true

[markup.tableOfContents]
startLevel = 2
endLevel = 6
ordered = false

########################### Output Format ##########################
[outputFormats]
[outputFormats.WebAppManifest]
mediaType = "application/manifest+json"
rel = "manifest"

############################# Modules ############################
[module]
[[module.mounts]]
source = "assets"
target = "assets"

[[module.mounts]]
source = "hugo_stats.json"
target = "assets/watching/hugo_stats.json"

############################# Build ##############################
[build]
noJSConfigInAssets = false
useResourceCacheWhen = 'fallback'
[build.buildStats]
enable = true
[[build.cachebusters]]
source = 'assets/watching/hugo_stats\.json'
target = 'style\.css'
[[build.cachebusters]]
source = '(postcss|tailwind)\.config\.js'
target = 'css'
[[build.cachebusters]]
source = 'assets/.*\.(js|ts|jsx|tsx)'
target = 'js'
[[build.cachebusters]]
source = 'assets/.*\.(css|scss|sass)'
target = 'css'
[[build.cachebusters]]
source = 'data/.*\.(.*)$'
target = 'css'
[[build.cachebusters]]
source = 'assets/.*\.(.*)$'
target = '$1'

############################ Caches ##############################
[caches]
[caches.images]
dir = ":resourceDir/_gen"
maxAge = "720h"

[caches.assets]
dir = ":resourceDir/_gen"
maxAge = "720h"

#################################### Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/css/bootstrap.min.css"
lazy = false

[[params.plugins.css]]
link = "plugins/ionicons/css/ionicons.min.css"
lazy = true

[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.min.css"
lazy = true

[[params.plugins.css]]
link = "plugins/slick/slick.css"
lazy = false


# JS Plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
lazy = false

[[params.plugins.js]]
link = "plugins/bootstrap/js/bootstrap.min.js"
lazy = false

[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
lazy = false

[[params.plugins.js]]
link = "plugins/magnific-popup/magnific-popup.min.js"
lazy = true

[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
lazy = true

[[params.plugins.js]]
link = "plugins/webfont/webfont-loader-2.js"
lazy = false

[[params.plugins.js]]
link = "plugins/glightbox/glightbox.js"
lazy = false

[[params.plugins.js]]
link = "js/gallery-slider.js"
lazy = true
